### ISSUE TITLE
split -f catalog.json -e catalog.* fails

### ISSUE THREAD

**Issue by fsuits** [IBM/compliance-trestle#423]
The lower level code requires a json path with 2 or more elements and this ends up just being catalog

**Comment by butler54** [comment]
@fsuits I'm pretty sure we fixed this?

**Comment by fsuits** [comment]
@butler54 this is still an issue - I'm looking at split currently.
For catalog.* I guess we want catalog.json to be stripped to contain only the uuid, and all other items are split off?
